create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text default 'student' check (role in ('student','admin')),
  plan text default 'free' check (plan in ('free','plus','pro','mentor')),
  branch text,
  level text,
  goal text,
  study_days text,
  created_at timestamptz default now()
);

create table if not exists videos (
  id bigint generated by default as identity primary key,
  title text not null,
  youtube_id text not null,
  branch text not null,
  topic text,
  level text,
  plan text default 'free' check (plan in ('free','plus','pro')),
  sort_order int default 0,
  pdf_url text,
  created_at timestamptz default now()
);

create table if not exists progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  video_id bigint references videos(id) on delete cascade,
  completed boolean default false,
  watched_seconds int default 0,
  updated_at timestamptz default now()
);

alter table profiles enable row level security;
alter table videos enable row level security;
alter table progress enable row level security;

create policy "students read own profile" on profiles for select using (auth.uid() = id);
create policy "students update own profile" on profiles for update using (auth.uid() = id);
create policy "everyone can read published videos" on videos for select using (true);
create policy "students read own progress" on progress for select using (auth.uid() = user_id);
create policy "students write own progress" on progress for insert with check (auth.uid() = user_id);
