-- Olympion Lab initial schema

create extension if not exists "pgcrypto";

create type public.user_role as enum ('student', 'admin');
create type public.plan_type as enum ('free', 'plus', 'pro', 'mentor');
create type public.branch_type as enum ('physics', 'chemistry', 'math', 'biology');
create type public.payment_status as enum ('created', 'pending', 'paid', 'failed', 'refunded', 'callback_received');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  role public.user_role not null default 'student',
  plan public.plan_type not null default 'free',
  branch public.branch_type,
  level text,
  goal text,
  study_days text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  title text not null,
  youtube_id text not null,
  branch public.branch_type not null,
  topic text,
  level text,
  plan_required public.plan_type not null default 'free',
  sort_order int not null default 0,
  description text,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pdf_notes (
  id bigint generated by default as identity primary key,
  title text not null,
  branch public.branch_type not null,
  topic text,
  file_url text not null,
  plan_required public.plan_type not null default 'plus',
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  watched_seconds int not null default 0,
  duration_seconds int not null default 0,
  completed boolean not null default false,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(user_id, video_id)
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan public.plan_type not null,
  status text not null default 'active',
  provider text not null default 'manual',
  provider_customer_id text,
  started_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  provider text not null,
  provider_payment_id text,
  plan text,
  amount_cents int not null default 0,
  currency text not null default 'TRY',
  status public.payment_status not null default 'created',
  raw jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_videos_updated_at on public.videos;
create trigger set_videos_updated_at before update on public.videos
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.videos enable row level security;
alter table public.pdf_notes enable row level security;
alter table public.user_progress enable row level security;
alter table public.subscriptions enable row level security;
alter table public.payments enable row level security;
alter table public.ai_messages enable row level security;
alter table public.admin_audit_logs enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Profiles
drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin" on public.profiles
for select using (auth.uid() = id or public.is_admin());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
for update using (auth.uid() = id) with check (auth.uid() = id);

-- Videos
drop policy if exists "videos_select_published_or_admin" on public.videos;
create policy "videos_select_published_or_admin" on public.videos
for select using (is_published = true or public.is_admin());

drop policy if exists "videos_admin_all" on public.videos;
create policy "videos_admin_all" on public.videos
for all using (public.is_admin()) with check (public.is_admin());

-- PDF notes
drop policy if exists "pdf_select_published_or_admin" on public.pdf_notes;
create policy "pdf_select_published_or_admin" on public.pdf_notes
for select using (is_published = true or public.is_admin());

drop policy if exists "pdf_admin_all" on public.pdf_notes;
create policy "pdf_admin_all" on public.pdf_notes
for all using (public.is_admin()) with check (public.is_admin());

-- Progress
drop policy if exists "progress_select_own_or_admin" on public.user_progress;
create policy "progress_select_own_or_admin" on public.user_progress
for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "progress_insert_own" on public.user_progress;
create policy "progress_insert_own" on public.user_progress
for insert with check (auth.uid() = user_id);

drop policy if exists "progress_update_own" on public.user_progress;
create policy "progress_update_own" on public.user_progress
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Subscriptions
drop policy if exists "subscriptions_select_own_or_admin" on public.subscriptions;
create policy "subscriptions_select_own_or_admin" on public.subscriptions
for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "subscriptions_admin_all" on public.subscriptions;
create policy "subscriptions_admin_all" on public.subscriptions
for all using (public.is_admin()) with check (public.is_admin());

-- Payments
drop policy if exists "payments_select_own_or_admin" on public.payments;
create policy "payments_select_own_or_admin" on public.payments
for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "payments_insert_own" on public.payments;
create policy "payments_insert_own" on public.payments
for insert with check (auth.uid() = user_id or user_id is null);

drop policy if exists "payments_admin_all" on public.payments;
create policy "payments_admin_all" on public.payments
for all using (public.is_admin()) with check (public.is_admin());

-- AI messages
drop policy if exists "ai_messages_select_own_or_admin" on public.ai_messages;
create policy "ai_messages_select_own_or_admin" on public.ai_messages
for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "ai_messages_insert_own" on public.ai_messages;
create policy "ai_messages_insert_own" on public.ai_messages
for insert with check (auth.uid() = user_id);

-- Audit logs
drop policy if exists "audit_admin_select" on public.admin_audit_logs;
create policy "audit_admin_select" on public.admin_audit_logs
for select using (public.is_admin());

drop policy if exists "audit_admin_insert" on public.admin_audit_logs;
create policy "audit_admin_insert" on public.admin_audit_logs
for insert with check (public.is_admin());

insert into public.videos (title, youtube_id, branch, topic, level, plan_required, sort_order, description, is_published)
values
('Fizik Olimpiyatı 2025 Soru 1', 'QYXfaRyjdws', 'physics', 'Mekanik', 'beginner', 'free', 1, 'Kuvvet diyagramı ve temel mekanik sezgisi.', true),
('Fizik Olimpiyatı 2025 Soru 2', 'kYX0zN53jEo', 'physics', 'Mekanik', 'intermediate', 'plus', 2, 'Enerji ve momentum ayrımı.', true),
('Kimyasal Dengeye Giriş', 'jYq7kC4DIfg', 'chemistry', 'Denge', 'beginner', 'free', 3, 'Le Chatelier ilkesine sezgisel giriş.', true)
on conflict do nothing;
